Add:sample.html
taro-kuroda-5228/django_auto_trading pull request #3
Opened 2022-01-10 12:25 UTC by taro-kuroda-5228

すいません、たぶん違うとおもうのですが、一応"http://127.0.0.1:8000/static/sample.html"は開けます。
参考写真のようにするということは、
⑴会社概要の説明をmodels.TextFieldでmodel.pyに設定、そのあとどこかから内容を取ってくる
⑵株価推移のグラフはmatplotlibを使用しdatamart.pyから表示、その際name, symbol_data, raw_data, datamart.pyをすべてdjango_auto_trading/auto_tradingディレクトリに持ってくる
⑶翌日の株価up or downはmodel.pyの結果から、そのためmodel.pyもdjango_auto_trading/auto_tradingディレクトリに持ってくる
⑷前日の株価一覧はmodels.TextFieldでmodel.pyに設定、CSSで形を整える
という流れでしょうか？

2022-01-11 13:55 UTC, atsushimemet requested changes
@taro-kuroda-5228 
概ねOKです!質問も素晴らしかったです!
一部修正しましょう。
とてもよかったです。

2022-01-11 13:55 UTC, atsushimemet commented on auto_trading/static/sample.html
> +    </div>
@taro-kuroda-5228 
想定した通りのコードであったので、よかったです。
ただ、この後のフローに合わせるためにbodyタグ内を下記に変更してください。
```
<header class="header">
    <div class="title">
        Auto Trading
    </div>
    <div class="top_page">
        <a href="/auto_trading_web/" class="header__link">トップページ</a>
    </div>
</header>
<main class="main">

        <div class="company_name">
            <h3><b>マイクロソフト</b></h3>
        </div>

        <div class="company_name_below">
            <span class="company_name_below__content">翌日の株価: <b class="highlighted">up</b></span>
            <span class="company_name_below__content">ティッカーシンボル: msft</span>
        </div>

        <div class="company_desc">
            International Business Machines Corporation (IBM) is an American multinational technology company
            headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded
            in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International
            Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware,
            middleware and software, and provides hosting and consulting services in areas ranging from mainframe
            computers to nanotechnology. IBM is also a major research organization, holding the record for most annual
            U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the
            automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the
            relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM).
            The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and
            1970s.
        </div>

        <div class="company_last_30days_closing_price">
            <h4><b>直近30日間の終値の推移</b></h4>
            <img src="/static/images/ticker.png" alt="no" class="image">
        </div>

        <div class="company_yesterday_price">
            <h4><b>前日の株価</b></h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">items</th>
                        <th scope="col">value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">datetime</th>
                        <td>2021-12-23</td>
                    </tr>
                    <tr>
                        <th scope="row">open</th>
                        <td>336</td>
                    </tr>
                    <tr>
                        <th scope="row">high</th>
                        <td>332</td>
                    </tr>
                    <tr>
                        <th scope="row">low</th>
                        <td>334</td>
                    </tr>
                    <tr>
                        <th scope="row">volume</th>
                        <td>19,617,800</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </main>
```

- /static/images/ticker.pngはリンク切れで構いません。
-

2022-01-11 13:55 UTC, atsushimemet commented on auto_trading/urls.py
> +    path("", views.sample, name="sample"),
@taro-kuroda-5228 
viewsから呼び出さなくて構いません。
検索バーに`http://127.0.0.1:8000/static/sample.html`と入力して、該当ページが表示されるようにしてください。

HINT: settings.py
```
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
```

2022-01-11 14:00 UTC, atsushimemet commented
> すいません、たぶん違うとおもうのですが、一応"[http://127.0.0.1:8000/static/sample.html"は開けます。](http://127.0.0.1:8000/static/sample.html%22%E3%81%AF%E9%96%8B%E3%81%91%E3%81%BE%E3%81%99%E3%80%82) 参考写真のようにするということは、
 ⑴会社概要の説明をmodels.TextFieldでmodel.pyに設定、そのあとどこかから内容を取ってくる
 ⑵株価推移のグラフはmatplotlibを使用しdatamart.pyから表示、その際name, symbol_data, raw_data, datamart.pyをすべてdjango_auto_trading/auto_tradingディレクトリに持ってくる 
⑶翌日の株価up or downはmodel.pyの結果から、そのためmodel.pyもdjango_auto_trading/auto_tradingディレクトリに持ってくる 
⑷前日の株価一覧はmodels.TextFieldでmodel.pyに設定、CSSで形を整える という流れでしょうか？

(1), (4) ここのmodel.pyはmodels.pyのことを指してますか?黒田さんの作成されたauto_tradingモジュール内のmodel.pyのことを指してますか?
(2), (3) django_auto_trading/auto_trading/baseの下にname, symbol_data, raw_data, datamart.py, model.pyを配置する予定です。

2022-01-11 21:15 UTC, taro-kuroda-5228 commented
すいません、⑴⑷のmodels.pyはdjangoで作られたdjango_auto_tradingディレクトリ内のmodels.pyです！
了解しました！ありがとうございます！

2022-01-11 23:04 UTC, atsushimemet commented
(1)(4) に関して承知しました。現在、models.pyの使用は考えておりません。djangoに慣れていただくため、views.py内での実装をイメージしております。なおCSSでの整形は行う予定です。

2022-01-12 02:35 UTC, taro-kuroda-5228 commented
了解しました！ありがとうございます！

2022-01-12 23:02 UTC, taro-kuroda-5228 commented
修正しましたので御手隙の際に添削お願いします！

2022-01-12 23:49 UTC, atsushimemet approved these changes
+1

2022-01-13 02:28 UTC, merged