Add: forms
taro-kuroda-5228/django_auto_trading pull request #6
Opened 2022-01-15 00:52 UTC by taro-kuroda-5228

すいません、ここまではこれたのですが、index.htmlに入力されたティッカーシンボルをforms.pyのフィールドtickerに代入する方法がよく分かりませんでした😓

2022-01-15 13:04 UTC, atsushimemet commented
@taro-kuroda-5228 ここは非常に混乱しやすいポイントなので、明日の講義で順を踏んでいきましょう！

2022-01-16 06:55 UTC, taro-kuroda-5228 commented
一応出来上がりましたので添削お願いします！
resultsに関してはtickerを引数に取ってしまうとエラーが出てしまうので現時点では抜いてあります！

2022-01-16 23:33 UTC, atsushimemet requested changes
@taro-kuroda-5228 素晴らしい実装です。質問少なく、ここまでできていらっしゃってかなり驚いてます。日頃の研鑽の賜物ですね。お疲れ様でした。

軽微な修正のみ、ご依頼しております。どうぞ宜しくお願い致します。

2022-01-16 23:33 UTC, atsushimemet commented on auto_trading/urls.py
> +    path("inputs", views.inputs, name="inputs"),
pathの第一引数のurlの文字列の末尾にはスラッシュを入れましょう！

2022-01-16 23:33 UTC, atsushimemet commented on auto_trading/urls.py
> +    path("results", views.results, name="results"),
pathの第一引数のurlの文字列の末尾にはスラッシュを入れましょう！

2022-01-16 23:44 UTC, taro-kuroda-5228 commented
修正させて頂きました！

2022-01-19 00:19 UTC, atsushimemet reviewed
+1

2022-01-19 00:19 UTC, atsushimemet approved these changes

2022-01-19 00:33 UTC, merged