Add:refoctoring files
taro-kuroda-5228/django_auto_trading pull request #8
Opened 2022-01-25 07:52 UTC by taro-kuroda-5228

ページの形が微妙ですが、とりあえず何となくの外観は出来上がりました！
一つご質問があります！
index.htmlのformに入力されたtickerをviews.imputに渡し、それを引数tickerとしてviews.resultsに渡す方法が良く分かりませんでした、、、
urlsをpath("results/str:ticker”）とし、views.resultsに引数tickerとして渡すとエラーが出てしまいます💦

2022-01-25 13:35 UTC, atsushimemet requested changes
@taro-kuroda-5228 
- いくつか修正点を指摘させていただいたので修正しましょう!
- views.resultsに引数tickerとして渡すとエラーが出る件は、inputs関数を下記のように変更すると、解決すると思いますが、どうでしょう?
```
def inputs(request):
    ticker = request.POST.get("ticker")
    form = InputForm(request.POST)
    is_valid = form.is_valid()
    if is_valid:
        return HttpResponseRedirect(reverse("auto_trading_web:results", args=(ticker,)))
    return HttpResponseNotFound("<h1>Page not found</h1>")
- コメント、docstringがあると、もっと良いコードになると思います。
```

2022-01-25 13:35 UTC, atsushimemet commented on auto_trading/views.py
> +from auto_trading.local_settings_amend import APIkey
@taro-kuroda-5228 
コードを見る感じ、APIkeyがapi_keyを保持し、api_keyが黒田さんのalpha_vantageのapiキーの値を保持していると思います。
特に理由がなければ、その値は、APIkeyに持たせてください。
またグローバル変数として扱う場合、変数名は大文字で書きます。修正しましょう。
```
× APIkey
○ API_KEY
```

2022-01-25 13:35 UTC, atsushimemet commented on auto_trading/views.py
> +    api_key = APIkey.api_key
@taro-kuroda-5228 
前述の変更に合わせた形で修正しましょう。

2022-01-25 13:35 UTC, atsushimemet commented on auto_trading/views.py
> +    api_key = APIkey.api_key
@taro-kuroda-5228 
前述の変更に合わせた形で修正しましょう。

2022-01-25 13:35 UTC, atsushimemet commented on auto_trading/views.py
> +def get_compnay_name():
@taro-kuroda-5228 
本関数はpandasのDataFrameを返します。
type hintを書きましょう。

2022-01-25 13:35 UTC, atsushimemet commented on auto_trading/views.py
> +        my_list = list(cr)
@taro-kuroda-5228 
一度csvに変換している理由を教えて頂けると助かります!
下記のようなコードを想定してました。
```
    url = "https://www.alphavantage.co/query?function=LISTING_STATUS&apikey=demo"
    r = requests.get(url)
    header = r.text.split("\r\n")[0].split(",")
    data = r.text.split("\r\n")[1:]
    data = [row.split(",") for row in data]
    df = pd.DataFrame(data, columns=header)
```

2022-01-25 13:35 UTC, atsushimemet commented on .gitignore
> +local_settings_amend.py
@taro-kuroda-5228 
この記述の下部に
*.pngを入れて、画像ファイルがgitの管理に含まれないようにしましょう。

2022-01-25 13:35 UTC, atsushimemet commented on auto_trading/views.py
> +def get_compnay_name():
@taro-kuroda-5228 
get_compnay_nameはget_company_nameに書き換え、他の該当箇所を修正しましょう。

2022-01-25 13:35 UTC, atsushimemet commented on auto_trading/views.py
> +    company_name = get_compnay_name().to_html()
@taro-kuroda-5228 
追加の要望です。
company_nameから、tickerに対応する会社名の正式名称を抽出しましょう。
現在は上場企業全てのテーブルが出力される形式になっているかと思いますが、そのテーブルからtickerに対応する会社名の正式名称のみ抽出するようにしてください。

2022-01-26 08:03 UTC, taro-kuroda-5228 commented on auto_trading/views.py
> +        my_list = list(cr)
ここはalpha vantageの公式サイトに従った形です！

2022-01-26 08:17 UTC, taro-kuroda-5228 commented on auto_trading/views.py
> +    company_name = get_compnay_name().to_html()
修正します！

2022-01-26 08:17 UTC, taro-kuroda-5228 commented on auto_trading/views.py
> +def get_compnay_name():
了解しました！

2022-01-26 10:59 UTC, atsushimemet commented on auto_trading/views.py
> +        my_list = list(cr)
@taro-kuroda-5228 
alpha vantageの公式サイトを読んで、どのように理解されてcsvに変換していますか?
黒田さんのことなのでないと思いますが、もし何も考えることなしにコピペで
コードを記載されていたら危険信号なので、
念の為、csvに変換している理由を伺っております。

2022-01-26 12:20 UTC, taro-kuroda-5228 commented
@atsushimemet 
tickerを引数として渡す部分以外修正しました！

2022-01-27 03:45 UTC, atsushimemet commented
@taro-kuroda-5228 
> @taro-kuroda-5228 alpha vantageの公式サイトを読んで、どのように理解されてcsvに変換していますか? 黒田さんのことなのでないと思いますが、もし何も考えることなしにコピペで コードを記載されていたら危険信号なので、 念の為、csvに変換している理由を伺っております。

上記ご回答よろしくお願いします!

2022-01-27 08:16 UTC, taro-kuroda-5228 commented
結果的にほぼコピペなのですが、一応公式サイトに以下のような記載があり、JSONファイルよりもCSVファイルの方がメモリー効率が良いからという認識でした！

To ensure optimal API response time, this endpoint uses the CSV format which is more memory-efficient than JSON.

2022-01-27 13:03 UTC, atsushimemet commented
> 

@taro-kuroda-5228 
Goodです、最高です!このコピペであれば、全く問題ありません。マージしてしまってください。よろしくお願いします。

2022-01-27 13:03 UTC, atsushimemet approved these changes
@taro-kuroda-5228 
お疲れ様でした^^

2022-01-27 21:07 UTC, taro-kuroda-5228 commented
了解です！ありがとうございます！

2022-01-27 21:07 UTC, merged